# coding=utf-8
import time

ota_scenic_order_details_table = {
                "order_id":"",
                "third_order_id":"",
                "channel_id":"",
                "ota_bkstg_name":"",
                "platform_id":"",
                "channel_sub_id":"",
                "scenic_id":"",
                "scenic_name":"",
                "room_type_id":"",
                "room_type_name":"",
                "city_name":"",
                "check_in_date":"",
                "check_out_date":"",
                "book_ticket_count":"",
                "get_ticket_count":"",
                "contact_name":"",
                "contact_cellphone":"",
                "book_time":"",
                "total_amount":"",
                "invoice_postage":"",
                "total_cost":"",
                "commission":"",
                "order_status":"",
                "order_from":"",
                "is_malicious_order":"",
                "business_type":"",
                "guarantee_type":"",
                "billing_type":"",
                "billing_no":"",
                "pay_type":"",
                "pay_status":"",
                "scenic_back_status":"",
                "cash_back_status":"",
                "fax_status":"",
                "refund_rule":"",
                "user_remark":"",
                "finance_receipt_no":"",
                "reserved_col1":"",
                "reserved_col2":"",
                "reserved_col3":"",
                "reserved_col4":"",
                "reserved_col5":"",
                "crawl_time":time.strftime("%Y-%m-%d %H:%M:%S")
               }