# coding=utf-8
import time

channel_scenic_product_price= {
"id":"",
"channel_id":"",
"platform_id":"",
"scenic_id":"",
"scenic_ticket_class_id":"",
"scenic_ticket_type_id":"",
"scenic_product_id":"",
"agent_id":"",
"sell_date":"",
"ticket_price":"",
"selling_price":"",
"currency":"",
"preferential_desc":"",
"can_book":"",
"reserved_col1":"",
"reserved_col2":"",
"reserved_col3":"",
"reserved_col4":"",
"reserved_col5":"",
"crawl_version":"",
"crawl_time":"",
}

channel_scenic_products = {
"id":"",
"scenic_product_id":"",
"scenic_product_name":"",
"platform_id":"",
"channel_id":"",
"scenic_id":"",
"scenic_ticket_class_id":"",
"scenic_ticket_type_id":"",
"agent_id":"",
"agent_name":"",
"product_type":"",
"support_digital":"",
"product_url":"",
"desc":"",
"valid_start_date":"",
"valid_end_date":"",
"book_policy":"",
"change_policy":"",
"cancel_policy":"",
"admission_policy":"",
"fee_desc":"",
"valid_time_desc":"",
"use_desc":"",
"ticket_get_time":"",
"ticket_get_type":"",
"total_month_orders":"",
"total_history_orders":"",
"pay_type":"",
"pay_platform":"",
"use_integral":"",
"use_coupon":"",
"has_invoice":"",
"sort":"",
"lastest_book_info":"",
"current_visit_info":"",
"reserved_col1":"",
"reserved_col2":"",
"reserved_col3":"",
"reserved_col4":"",
"reserved_col5":"",
"crawl_version":"",
"crawl_time":"",
}

channel_scenic_ticket_types = {
"id":"","scenic_ticket_class_id":"","scenic_ticket_class_name":"","scenic_ticket_type_id":"",
"scenic_ticket_type_name":"","platform_id":"","channel_id":"","scenic_id":"","desc":"","remark":"",
"reserved_col1":"","reserved_col2":"","reserved_col3":"","reserved_col4":"","reserved_col5":"",
"crawl_version":"","crawl_time":"",
}