# coding=utf-8
import time

ota_hotel_table = {
                "hotel_front_id":"",
                "hotel_id":"",
                "hotel_name":"",
                "hotel_name_gb":"",
                "channel_id":-1,
                "ota_bkstg_name":"",
                "platform_id":-1,
                "channel_sub_id":-1,
                "channel_sub_name":"",
                "channel_sub_url":"",
                "type":"",
                "star":"",
                "country_name":"",
                "province_name":"",
                "city_name_cn":"",
                "city_name_gb":"",
                "address":"",
                "longitude":"",
                "latitude":"",
                "telephone":"",
                "fax":"",
                "group_belongs":"",
                "brand":"",
                "opening_time":"",
                "decorate_time":"",
                "storeys":"",
                "rooms":"",
                "check_in_time":"",
                "check_out_time":"",
                "url":"",
                "desc":"",
                "facility":"",
                "hotel_service":"",
                "has_parking_lot":-1,
                "has_restaurant":-1,
                "has_gym":-1,
                "order_confirm_time":"",
                "latest_booking_time":"",
                "latest_confirm_time":"",
                "is_invoice_supportted":"",
                "invoice_type":"",
                "invoice_desc":"",
                "status":"",
                "status_update_date":"",
                "reserved_col1":"",
                "reserved_col2":"",
                "reserved_col3":"",
                "reserved_col4":"",
                "reserved_col5":"",
                "crawl_time":time.strftime("%Y-%m-%d %H:%M:%S")
               }