# coding=utf-8
import time
ota_scenic_table = {
                "scenic_id":"",
                "scenic_name":"",
                "scenic_name_gb":"",
                "channel_id":"",
                "ota_bkstg_name":"",
                "platform_id":"",
                "channel_sub_id":"",
                "channel_sub_name":"",
                "channel_sub_url":"",
                "type":"",
                "level":"",
                "country_name":"",
                "province_name":"",
                "city_name_cn":"",
                "city_name_gb":"",
                "address":"",
                "longitude":"",
                "latitude":"",
                "telephone":"",
                "fax":"",
                "group_belongs":"",
                "url":"",
                "desc":"",
                "opening_time":"",
                "closeing_time":"",
                "status":"",
                "reserved_col1":"",
                "reserved_col2":"",
                "reserved_col3":"",
                "reserved_col4":"",
                "reserved_col5":"",
                "crawl_time":time.strftime("%Y-%m-%d %H:%M:%S")
               }