# coding=utf-8
import time
ota_scenic_ticket_type_table = {
                "scenic_ticket_type_id":"",
                "scenic_ticket_type_name":"",
                "channel_id":"",
                "ota_bkstg_name":"",
                "platform_id":"",
                "channel_sub_id":"",
                "scenic_id":"",
                "desc":"",
                "can_deliver":"",
                "need_contact_name_cn":"",
                "need_contact_name_py":"",
                "need_contact_cellphone":"",
                "need_contact_email":"",
                "need_contact_address":"",
                "need_traveler_name_cn":"",
                "need_traveler_name_gb":"",
                "need_traveler_name_py":"",
                "need_traveler_cellphone":"",
                "need_traveler_email":"",
                "need_traveler_address":"",
                "need_travel_certificate":"",
                "need_travel_sex":"",
                "need_travel_birth_date":"",
                "need_travel_birth_address":"",
                "traveler_info_desc":"",
                "is_use_date_limited":"",
                "status":"",
                "reserved_col1":"",
                "reserved_col2":"",
                "reserved_col3":"",
                "reserved_col4":"",
                "reserved_col5":"",
                "crawl_time":time.strftime("%Y-%m-%d %H:%M:%S")
               }